const CONSULTANT_REPOSITORY = 'CONSULTANT_REPOSITORY';
const ANSWER_REPOSITORY = 'ANSWER_REPOSITORY';
const QUESTION_REPOSITORY = 'QUESTION_REPOSITORY';

export { CONSULTANT_REPOSITORY, ANSWER_REPOSITORY, QUESTION_REPOSITORY };
