export enum providersEnum {
  CONSULTANT_REPOSITORY = 'CONSULTANT_REPOSITORY',
  ANSWER_REPOSITORY = 'ANSWER_REPOSITORY',
  QUESTION_REPOSITORY = 'QUESTION_REPOSITORY',
  VOTE_REPOSITORY = 'VOTE_REPOSITORY',
}
